baseURL = 'https://jesseburlamaque.github.io/jesseonjungle/'
locale = 'pt-BR'
title = 'JesseOnJungle'
theme = 'compost'
enableEmoji = true
enableRobotsTXT = true

[params]
  description = 'Geospatial Data Pipelines, Sensoriamento Remoto e Machine Learning.'
  colorScheme = 'light'
  mainSections = ['posts']

  [params.author]
    name = 'Jessé Burlamaque'
    image = 'img/author.jpg'
    bio = 'GIS Specialist | Geospatial Data Science | ML'
    links = [
      { github = 'https://github.com/jesseburlamaque' },
      { linkedin = 'https://www.linkedin.com/in/jesseburlamaque/' },
      { medium = 'https://medium.com/@jesseburlamaque' },
    ]

  [params.homepage]
    layout = 'page'
    showRecent = true

[build]
  writeStats = true

[[build.cachebusters]]
  source = "assets/watching/hugo_stats\\.json"
  target = "main\\.css"

[[build.cachebusters]]
  source = "(postcss|tailwind)\\.config\\.js"
  target = "css"

[[build.cachebusters]]
  source = "assets/.*\\.(js|ts|jsx|tsx)"
  target = "js"

[[build.cachebusters]]
  source = "assets/.*\\.(.*)$"
  target = "$1"

[minify]
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepQuotes = true
